apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    containerImage: icr.io/cpopen/ds-operator@sha256:ce07b444123126d8bbabc48f20a36d3a0280dc7d3b4a09b14d23335c81ba6dad
    alm-examples: |-
      [
        {
          "apiVersion": "ds.cpd.ibm.com/v1",
          "kind": "DataStage",
          "metadata": {
            "name": "datastage"
          },
          "spec": {
            "license": {
              "accept": false
            },
            "fileStorageClass": "managed-nfs-storage",
            "scaleConfig": "small"
          }
        }
      ]
    capabilities: Seamless Upgrades
    cloudpakId: 49a42b864bb94569bef0188ead948f11
    cloudpakName: IBM DataStage Enterprise Plus Cartridge for IBM Cloud Pak for Data
    description: The IBM DataStage Operator is used to deploy IBM DataStage services
    features.operators.openshift.io/disconnected: "false"
    features.operators.openshift.io/fips-compliant: "false"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operators.operatorframework.io/builder: operator-sdk-v1.4.2
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.s390x: supported
    operatorframework.io/os.linux: supported
    operatorframework.io/suggested-namespace: ibm-common-services
    operators.openshift.io/infrastructure-features: '["Disconnected"]'
    olm.skipRange: '>=1.0.0 <7.0.0'
    nss.operator.ibm.com/managed-operators: ibm-cpd-datastage-operator
  name: ibm-cpd-datastage-operator.v7.0.0
  namespace: placeholder
spec:
  relatedImages:
  - name: ds-operator
    image: icr.io/cpopen/ds-operator@sha256:ce07b444123126d8bbabc48f20a36d3a0280dc7d3b4a09b14d23335c81ba6dad
  - name: ds-canvas
    image: cp.icr.io/cp/cpd/ds-canvas@sha256:fc9fe81177b9572b46046cd874323d5c78dca8630d1d938c82d4bb8a1ff24b09
  - name: ds-cas-lite
    image: cp.icr.io/cp/cpd/ds-cas-lite@sha256:3c83e1d351014ad5a35e94974928952c071df57e14395f5ef4bd68e1458018af
  - name: ds-flows
    image: cp.icr.io/cp/cpd/ds-flows@sha256:2ceda85ffd622830c861841155888fb341afadd01ac72959e9179a7ab2d9859e
  - name: ds-nginx-proxy
    image: cp.icr.io/cp/cpd/ds-nginx-proxy@sha256:6d5fa2816cb3839202b48fca05f1c0bd50086dd6fa44b360ad712338de8b7955
  - name: ds-migration
    image: cp.icr.io/cp/cpd/ds-migration@sha256:3ef802dac5d94fde8fdd680ec549df576b7e78e5fc38bfd10646516b4b4290ba
  - name: ds-assets
    image: cp.icr.io/cp/cpd/ds-assets@sha256:3e83c60a635e98a2eed647d600bc4278940f95a049a5a8e7e0bff3f249d301d4
  - name: ds-px-compute
    image: cp.icr.io/cp/cpd/ds-px-compute@sha256:ac4e086fc5067e58a748d32352f451cde436004a825168f8c42dc419128156b4
  - name: ds-px-runtime
    image: cp.icr.io/cp/cpd/ds-px-runtime@sha256:5a2dd820759d64581dd1d3d506f08103be97ea102f72b8ad31c8720601b020be
  - name: qs-ruleset
    image: cp.icr.io/cp/cpd/qs-ruleset@sha256:fcf1e650c582bf345edafd351933b95612b7833482ac4e945c0ba679f580366d
  - name: ds-runtime
    image: cp.icr.io/cp/cpd/ds-runtime@sha256:b9302bad0ed5ec84db781c5ad745a8c6820a436368815966a3e063fd161c1c08
  - name: ds-dataservice
    image: cp.icr.io/cp/cpd/ds-dataservice@sha256:7232589d98edd41060a096dc76bbe95503793250607f56735cce24848ca7b0e5
  - name: ds-metrics
    image: cp.icr.io/cp/cpd/ds-metrics@sha256:d5f749032f3d4ecaa6484c3839c5ead128fefe4aec82fef78d3d24ad6b892bde
  - name: ds-operator-ce07b444123126d8bbabc48f20a36d3a0280dc7d3b4a09b14d23335c81ba6dad-annotation
    image: icr.io/cpopen/ds-operator@sha256:ce07b444123126d8bbabc48f20a36d3a0280dc7d3b4a09b14d23335c81ba6dad
  - name: manager
    image: icr.io/cpopen/ds-operator@sha256:ce07b444123126d8bbabc48f20a36d3a0280dc7d3b4a09b14d23335c81ba6dad
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: DataStage
      name: datastages.ds.cpd.ibm.com
      description: 'Documentation: [IBM Knowledge Center](https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=services-datastage) License: [IBM DataStage Enterprise Cartridge for Cloud Pak for Data](https://ibm.biz/Bdahic),
        [IBM DataStage Enterprise Plus Cartridge for Cloud Pak for Data](https://ibm.biz/BdahsW)'
      version: v1
      specDescriptors:
      - description: 'You must read and accept the license terms to install the software IBM DataStage Enterprise Cartridge for Cloud Pak for Data(https://ibm.biz/Bdahic), IBM DataStage Enterprise Plus
          Cartridge for Cloud Pak for Data(https://ibm.biz/BdahsW).'
        displayName: License
        path: license
      - description: Indicate that you read and accept the license.
        displayName: Accept license
        path: license.accept
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:checkbox
        value:
        - false
      - description: Select the size for the DataStage installation.
        displayName: Size
        path: scaleConfig
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:select:small
        - urn:alm:descriptor:com.tectonic.ui:select:medium
        - urn:alm:descriptor:com.tectonic.ui:select:large
      - description: The block storage class to use for install. Used for RWO PVCs.
        displayName: Block Storage Class
        path: blockStorageClass
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes:StorageClass
      - description: The file storage class to use for install. Used for RWX PVCs.
        displayName: File Storage Class
        path: fileStorageClass
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes:StorageClass
    - kind: PXRuntime
      name: pxruntimes.ds.cpd.ibm.com
      description: 'Documentation [IBM Knowledge Center](https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=services-datastage) License [IBM DataStage Enterprise Plus Cartridge for Cloud Pak for Data](https://ibm.biz/BdahsW)'
      version: v1
  description: |-
    # Introduction
    Industry-leading batch and real-time data integration service for data engineers to build trusted pipelines (ETL/ELT) for AI and operational use cases across on-premises and hybrid cloud environments.
    With DataStage, you can design and run data flows that move and transform data anywhere, at any scale.
    No matter how complex your data landscape, DataStage can streamline your data movement costs and increase productivity. DataStage offers:
    <ul><li>A best-in-breed parallel processing engine that enables you to process your data where it resides</li><li>Automated job design</li><li>Simple integration with cloud data lakes, real-time data sources, relational databases, big data, and NoSQL data stores</li></ul>
    The DataStage service uses Cloud Pak for Data platform connections and integration points, with services like Data Virtualization, to simplify the process of connecting to and accessing your data.

    With DataStage, Data Engineers can use the simple user interface to build no-code/low-code data pipelines. The interface offers hundreds of functions and connectors that reduce development time and inconsistencies across pipelines. The interface also makes it easy to collaborate with your peers and control access to specific analytics projects.
    The service also provides automatic workload balancing to provide high performance pipelines that make efficient use of available compute resources.

    ## Details
    See [Details](https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=SSQNUZ_4.0/svc-welcome/dsent.html)

    ## Documentation

    [IBM Knowledge Center](https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=services-datastage)

    ## Installing
    To install the operator follow the the installation and configuration instructions within the [IBM Knowledge Center](https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=datastage-installing).

    ## Prerequisites

    - OpenShift Version >= 4.6
    - IBM Cloud Pak for Data >= 4.0.2
    - IBM Cloud Pak for Data Common Core Services (CCS) >= 2.0.2 (The DataStage service automatically installs the CCS if they are not already installed.)

    ### Resources Required

    See [Details](https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=requirements-hardware)

    ## Configuration

    To scale DataStage services, you can specify spec.scaleConfig in the DataStage custom resource to small, medium, or large.

    ## License
    [IBM DataStage Enterprise Cartridge for Cloud Pak for Data](https://ibm.biz/Bdahic)
    [IBM DataStage Enterprise Plus Cartridge for Cloud Pak for Data](https://ibm.biz/BdahsW)

    ## Limitations
    - Only the `x86-64` platform is supported by this operator.
    - See [Limitations and known issues in DataStage](https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=issues-datastage)

    ## SecurityContextConstraints Requirements
    Custom SecurityContextConstraints definition:
    ```
    apiVersion: security.openshift.io/v1
    kind: SecurityContextConstraints
    allowHostDirVolumePlugin: false
    allowHostIPC: false
    allowHostNetwork: false
    allowHostPID: false
    allowHostPorts: false
    allowPrivilegeEscalation: true
    allowPrivilegedContainer: false
    allowedCapabilities: null
    defaultAddCapabilities: null
    fsGroup:
      type: MustRunAs
    metadata:
      annotations:
        include.release.openshift.io/self-managed-high-availability: "true"
        kubernetes.io/description: restrict denies access to all host features and requires pods to be run with a UID, and SELinux context that are allocated to the namespace.  This is the most restrictive SCC and it is used by default for authenticated users.
        release.openshift.io/create-only: "true"
      name: restrict
    priority: null
    readOnlyRootFilesystem: false
    requiredDropCapabilities:
    - KILL
    - MKNOD
    - SETUID
    - SETGID
    runAsUser:
      type: MustRunAsRange
    seLinuxContext:
      type: MustRunAs
    supplementalGroups:
      type: RunAsAny
    users: []
    volumes:
    - configMap
    - downwardAPI
    - emptyDir
    - persistentVolumeClaim
    - projected
    - secret
    ```
  displayName: IBM DataStage
  icon:
  - base64data: "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAACXBIWXMAABYlAAAWJQFJUiTwAAAGfklEQVR4nO1bW4gcRRS9tYkkmZfBB4RgyyohBFkkakR/1NkPv1RMfhTxsbOoiEvnZQgJGvIwhoRgXJeMJkjIdKJ+CMomYBAMspMfEYxmxATfZMMoUWJwM88VwSvV1d3TXV392u2uneAeGOip6WH6nKo691bVHZjFLGbxvwYJJK+oBQBYCwDLuU/KAHAEqkVNpoA5tY2AAIBEfxF6DcR432m3rjlcOdzjaPQWQFEp4ZKAOA8qxCqoFifipSpGbnULebJRROAF6BH+CiM/FoI8RR4AzoOiLoyXqgcoW/3VuWYc3e3WtQ/EArCej0KI3juaBF8XRASnIcJcVwub83zP0+E9Ygx3MHp9LSdSHhR1JVSLx+JnbQf266xMwtYsptZApwMOA6HPT4zPAaxrgSe4BWDE7KDk+6FarNjayqCox4xpYhdhAAASFaA2kil7fZYbmiwhkOUEjZ4XicDBLYmi8nftgGpxu/AXFZW2b5syGz9Ui8ERyoac2i4BQiHIGK8cmuNjgsz8ePj1qGdvyERuTbMEBAsCT6i4PIGDlwleNcita5SAQEFgjBoSWO8yRl8BnPPcxEofMfIz2vPr6yUALAicX6u9PX9QGB04iEywwkWBtbrh8eKw6cIbJr1vVcw8hchtuFICxAKb5w7T02r7U4Ngvu1Eh9ACjBh5gImFutsralAYBD01loDcxglmeHaHR6PnRzKD1hPYhrwlAgex0yrqmZBZoB1lqBb7k6af3fSXTp7w6S4SrTacHbTfm1vdygOSMXsUqB2YFyIVprk9i/9hUTG+kyiymy+vY3OecnGYm4u8DssXokaBanEcAO4wiAWhbCRKiS6Gsi//SYkPMxIINhG02r5r3eR1YGBKLPIABlMElhoPCByf5gfHZSyHs1suFQDR8CUzraWXRKvtXehB3iTMZ4NOeAtgghJU1HGXAJLcPrv1D4O8K63V6nuu8ybPbqsA8msHJ4IFmEFkt/1eYBHJlc9r9d03+JOn64Y3MxNB2WrXCpDdcZH1PBvq9t7X6ruCyYdFV6bCmZ2/0eyu1DGujtvXX7sxNvIUXTcCMrt+LQBCieVvYDc9rf7qoljJU3SVAJndVYfb20TQ6tvjJ0/RNQJk9lxg5J3znYqgNbYu9ievqHljc6aDkPsJXSFAZu/4M3TY2+K75faNLTcl0vMmZtwEM6+ffxwIFoHgP5zpaY1XkiVPMaMjIPPGL6sAcS8AaduG/TU0yWlsvjlx8hQzJkB6+OeH2H4iTrIWa9gfbWzqfU7Wc8yIAOmRnx4ExI2IMEmcpvdBY2PvGpnPIl2A9P4fHgDEIQAyqe/W0OnORBhtbLh1s+znkSpA+q3v7zV2chzDHhFONF9aslPms5iQJkD6wHd3AuJjANDmVnYnm+uW7JP1HDykCJA+eK4PAB82hz2DLsKp5pqlB2U8gxcSFyD9ztmlgNAPiG3uuOqLprrsaNK/H4REBUgf+rYXEO8BgElu+/rr5tCyD5P87bAIJ0C1WA5VTWJD6vA3ixGxjziTHCrC2eaLt32SKKsISGQEpLTK9YBwC3V7titnDfsfmy/0nUqIy5QQuwCpI2eygLgIiDHsAY1TfHKh+Xzfl3JohUesAqTe/WoeIGZ1t3ceV11sPnv7uWSpTA2xCZB6/zRdvM9xJDlMhMutweXjMklFQWzL4daTKxAI/q0PfYL0RcPepVahe8lTOJx9wcen8oAw5i4zE5efEfPaWYkxF5DMo7tZrafvaibOYJoHN04BTpRdh4lRRWg9cTdJvXe6p/XUin+T4GtBUXuNyrRp1TG6p4BnmZm4Ha3Cg87hoyTyYU+wfesYnQIQwWFiVBHkYDSuOkZHFEBipi2dzK39yP2eGeCCjz7PA5AxW6xPnv306hgLvCc4w6AesmmP2kUIgO0EVlL/D3Dvo9QxPkp3mu1f5gQwKOhFlSFEcJy3iwsRdYj27ePDiLC4i7axsh57HaOr4EvgAZ35LqgsdQvAe4J8TKuO0T0FoDOkA8e0MWWcpzlXF4KjgK8A6I4O8jGtOkaBB/iXlHjebx1pCTCF/QRPKOoYRyxaHSMH92LIJYIPok6ZeHCEEyBKHeNxF137m/mffdpxa8+/nxiV2O46Pf26vfK+5K0wxjpG79WgTzaIHv/akBgFotYx0nuFZ43+y+GpiCAD0eoYK/q97DsuBG+ICI0RBcmS5FDorGPsmr/1zWIWs7iKAAD/ARzhBiS0VNI7AAAAAElFTkSuQmCC"
    mediatype: "image/png"
  install:
    spec:
      deployments:
      - name: ibm-cpd-datastage-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: ibm-cpd-datastage-operator
          strategy: {}
          template:
            metadata:
              labels:
                app.kubernetes.io/instance: ibm-cpd-datastage-operator
                app.kubernetes.io/managed-by: ibm-cpd-datastage-operator
                app.kubernetes.io/name: ibm-cpd-datastage-operator
                icpdsupport/module: ibm-cpd-datastage-operator
                icpdsupport/addOnId: datastage
                icpdsupport/app: operator
                intent: projected
                name: ibm-cpd-datastage-operator
              annotations:
                productID: "d8a97b146d6f4bf18f033db9105f87f1"
                cloudpakName: "IBM DataStage Extension for IBM Cloud Pak for Data"
                productName: "IBM DataStage Enterprise Plus for Cloud Pak for Data"
                productVersion: 5.1.0
                productMetric: FREE
            spec:
              hostNetwork: false
              hostPID: false
              hostIPC: false
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: beta.kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - s390x
              serviceAccountName: ibm-cpd-datastage-operator-sa
              containers:
              - args:
                - --zap-log-level
                - info
                - --max-concurrent-reconciles
                - "6"
                env:
                - name: ANSIBLE_GATHERING
                  value: explicit
                - name: WATCH_NAMESPACE
                  valueFrom:
                    configMapKeyRef:
                      key: namespaces
                      name: namespace-scope
                      optional: true
                - name: OPERATOR_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: icr.io/cpopen/ds-operator@sha256:ce07b444123126d8bbabc48f20a36d3a0280dc7d3b4a09b14d23335c81ba6dad
                livenessProbe:
                  httpGet:
                    path: /readyz
                    port: 6789
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /healthz
                    port: 6789
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  requests:
                    cpu: 100m
                    memory: 256Mi
                  limits:
                    cpu: 500m
                    memory: 1024Mi
                securityContext:
                  runAsNonRoot: true
                  privileged: false
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: false
                  capabilities:
                    drop:
                    - ALL
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          - batch
          - extensions
          - apps
          - policy
          - rbac.authorization.k8s.io
          - autoscaling
          - route.openshift.io
          - authorization.openshift.io
          - networking.k8s.io
          resources:
          - secrets
          - pods
          - pods/exec
          - pods/log
          - jobs
          - configmaps
          - deployments
          - deployments/scale
          - statefulsets
          - statefulsets/scale
          - replicasets
          - services
          - persistentvolumeclaims
          - persistentvolumes
          - cronjobs
          - pods/exec
          - serviceaccounts
          - namespaces
          - roles
          - rolebindings
          - horizontalpodautoscalers
          - routes
          - routes/custom-host
          - jobs/status
          - pods/status
          - networkpolicies
          verbs:
          - apply
          - create
          - get
          - delete
          - watch
          - update
          - edit
          - list
          - patch
        - apiGroups:
          - ds.cpd.ibm.com
          - ccs.cpd.ibm.com
          - wspipelines.cpd.ibm.com
          resources:
          - ccs
          - ccs/status
          - ccs/finalizers
          - datastages
          - datastages/status
          - datastages/finalizers
          - pxruntimes
          - pxruntimes/status
          - pxruntimes/finalizers
          - wspipelines
          - wspipelines/status
          - wspipelines/finalizers
          verbs:
          - apply
          - edit
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - zen.cpd.ibm.com
          resources:
          - zenservices
          - zenextensions
          - zenextensions/status
          - zenextensions/finalizers
          verbs:
          - create
          - apply
          - edit
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - operator.ibm.com
          resources:
          - operandrequests
          - operandregistries
          - operandconfigs
          - operandbindinfos
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
          - delete
          - use
        serviceAccountName: ibm-cpd-datastage-operator-sa
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - DataStage
  - Analytics
  - Cloud Pak
  - Data
  - Cloud Pak for Data
  - IBM
  maintainers:
  - name: IBM
    email: cp4d@ibm.com
  maturity: alpha
  provider:
    name: IBM
    url: https://www.ibm.com/in-en/products/cloud-pak-for-data
  version: 7.0.0
  #replaces: ibm-cpd-datastage-operator.v1.0.3
